#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-plexus-cipher
Version  : 1.4
Release  : 1
URL      : https://repo1.maven.org/maven2/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
Source0  : https://repo1.maven.org/maven2/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
Source1  : https://repo1.maven.org/maven2/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.pom
Source2  : https://repo1.maven.org/maven2/org/sonatype/plexus/plexus-cipher/1.7/plexus-cipher-1.7.jar
Source3  : https://repo1.maven.org/maven2/org/sonatype/plexus/plexus-cipher/1.7/plexus-cipher-1.7.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-plexus-cipher-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-plexus-cipher package.
Group: Data

%description data
data components for the mvn-plexus-cipher package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/plexus/plexus-cipher/1.7
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/plexus/plexus-cipher/1.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/plexus/plexus-cipher/1.7
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/plexus/plexus-cipher/1.7


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
/usr/share/java/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.pom
/usr/share/java/.m2/repository/org/sonatype/plexus/plexus-cipher/1.7/plexus-cipher-1.7.jar
/usr/share/java/.m2/repository/org/sonatype/plexus/plexus-cipher/1.7/plexus-cipher-1.7.pom
